_wandb:
    value:
        cli_version: 0.19.7
        code_path: code/duckiesim/rl/ppo.py
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.8.20
            "5": 0.19.7
            "8":
                - 5
            "12": 0.19.7
            "13": linux-x86_64
anneal_lr:
    value: true
batch_size:
    value: 2048
capture_video:
    value: false
clip_coef:
    value: 0.1
clip_vloss:
    value: true
cuda:
    value: true
ent_coef:
    value: 0.01
env_id:
    value: DuckietownDiscrete-v0
exp_name:
    value: ppo
gae_lambda:
    value: 0.95
gamma:
    value: 0.99
learning_rate:
    value: 0.00025
max_grad_norm:
    value: 0.5
minibatch_size:
    value: 512
norm_adv:
    value: true
num_envs:
    value: 1
num_iterations:
    value: 4882
num_minibatches:
    value: 4
num_steps:
    value: 2048
seed:
    value: 1
target_kl:
    value: null
torch_deterministic:
    value: true
total_timesteps:
    value: 10000000
track:
    value: true
update_epochs:
    value: 4
vf_coef:
    value: 0.5
wandb_entity:
    value: null
wandb_project_name:
    value: DuckieTownRL
